lang: pt   

project:
  type: book

book:
  title: "CENSO SUAS 2022"
  subtitle: ANÁLISE DOS COMPONENTES DA POLÍTICA NACIONAL DE ASSISTÊNCIA SOCIAL
#  author:
#    - Secretaria de Avaliação, Gestão da Informação e Cadastro Único
#    - Secretaria Nacional de Assistência Social
#    - Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome
#  date: "21/06/2024"
  cover-image: cover.png
  favicon: cover.png
  repo-url: https://github.com/Sagicad-MDS/Publicacoes-Censo-SUAS
  repo-branch: master
  repo-subdir: "Publicação 2022 livro HTML"
  repo-actions: [source, issue]
  repo-link-target: "_blank"
  chapters:
    - index.qmd
    - apresentacao.qmd
    - metodologia.qmd
    - gestao.qmd
    - unidades.qmd
    - servicos.qmd
    - rh.qmd
    - participacao.qmd
    - references.qmd
    - creditos.qmd

bibliography: references.bib

toc: true
toc-title: Sumário

execute:
  echo: false
  message: false
  warning: false
  cache: false

crossref:
  fig-title: Gráfico     # (default is "Figure")
  tbl-title: Tabela     # (default is "Table")
#  title-delim: "."   # (default is ":")
  fig-prefix: Gráfico   # (default is "Figure")
  tbl-prefix: Tabela    # (default is "Table")
#  ref-hyperlink: false # (default is true)
#  chapters: false

format:
  html:
    mainfont: "Rawline, Raleway, sans-serif"
    fontsize: 14px
    fontcolor: "#333333"
    linkcolor: "#1351B4"
    linestretch: 1.45
    backgroundcolor: "#ffffff"
    link-external-icon: true
    link-external-newwindow: true
    include-in-header:
      - text: |
          <link href="https://fonts.cdnfonts.com/css/rawline" rel="stylesheet">
          <script src="responsive-height.js"></script>

editor: visual
