# Créditos {.unnumbered}

## Expediente {.unnumbered}

Presidente da República Federativa do Brasil\
**Luiz Inácio Lula da Silva**

Ministro de Estado do Desenvolvimento e Assistência Social, Família e Combate à Fome\
**Wellington Dias**

Secretário-Executivo\
**Osmar Ribeiro de Almeida Júnior**

Secretária de Avaliação, Gestão da Informação e Cadastro Único\
**Letícia Bartholo de Oliveira e Silva**

Secretária Nacional de Renda de Cidadania\
**Eliane Aquino Custodio**

Secretário Nacional de Assistência Social\
**André Quintão Silva**

Secretária Extraordinária de Combate à Pobreza e à Fome\
**Valéria Torres Amaral Burity**

Secretária Nacional de Segurança Alimentar e Nutricional\
**Lilian dos Santos Rahal**

Secretário de Inclusão Socioeconômica\
**Luiz Carlos Everton de Farias**

Secretária Nacional de Cuidados e Família\
**Laís Wendel Abramo**

## Ficha Técnica {.unnumbered}

### Coordenação-geral da Publicação do Censo SUAS 2022 {.unnumbered}

**Diretoria de Monitoramento e Avaliação - DMA/SAGICAD:**

-   Joana Simões de Melo Costa: Diretora de Monitoramento e Avaliação
-   Shirley de Lima Samico: Assessora Técnica do SUAS

**Diretoria de Gestão do SUAS -- DGSUAS/SNAS**

-   Clara Carolina de Sá: Diretoria de Gestão do SUAS
-   Elizangela Cardoso de Araujo Silva: Coordenadora Geral de Vigilância Socioassistencial

### Concepção, Planejamento e participação em reuniões {.unnumbered}

Ana Angelica Campelo de Albuquerque e Melo, Ana Carolina Cambeses, Ana Gabriela Sambiase, Ana Paula Campos, Clara Carolina de Sá, Dionara Borges, Edgilson Tavares de Araujo, Elizangela Cardoso de Araujo Silva, Fabio Santos de Gusmão Lobo, Ieda Castro, Joana Simões de Melo Costa, Lais Maranhão Santos Mendonça, Lucas Loureiro Lino, Luciano Márcio Freitas de Oliveira, Marcelo Gomes Gadelha, Marcelo Sebatião de Oliveira, Marcílio Marquesini Ferrari, Mariana Peixoto, Paulo Clemente, Raimundo Nonato, Raquel Maria Soares Freitas, Ricardo Lovatel, Rogério Schmidt Campos, Sabrina Medeiros Borges, Shirley Samico, Simone Alburquerque, Simone de Castro Holanda, Thiago Silvino Rocha Oliveira, Ullysses da Silva Ferreira, Valdson Silva Cleto, Vinicius Pawlowski e Zilane Cristina Oliveira de Andrade.

### Desenvolvimento de aplicativos informatizados, coleta e tratamento de dados {.unnumbered}

Caio Nakashima, Carlos Henrique Santana, Carlos Brasileiro, Cristiane Silva de Moura, Danilo Galvão da Cunha, Davi Lopes Carvalho, Dionara Borges, Érika Paes Latim Castro, Frederico Palma, Marcelo do Nascimento Saraiva, Marcelo Gadelha, Marcos Coimbra, Murilo da Silva Mascarenhas de Morais, Paulo Clemente, Pedro Henrique Ribeiro Ferreira, Ricardo Carvalho, Roberto Wagner, Tiago Hackbarth.

### Desenvolvimento de projeto de programação para análise de dados e produção da publicação {.unnumbered}

Valdson Silva Cleto

### Concepção e organização de textos: {.unnumbered}

Clara Carolina de Sá, Elizangela Cardoso de Araújo Silva e Shirley Samico.

### Elaboração e revisão dos textos {.unnumbered}

Shirley Samico, Valdson Silva Cleto, Erica Moreira e Zilane Andrade.

