# Apresentação {.unnumbered}

## A Assistência Social no Brasil {.unnumbered}

É muito real a presença do SUAS na vida do povo brasileiro. Conquistamos um Sistema Único que tem vinculação com 37% da população inserida no Cadastro Único. A política de Assistência Social nas últimas décadas carrega uma conquista da sociedade brasileira através de um projeto de seguranças sociais afiançadas por meio da proteção, vigilância e defesa de direitos. Parte desse projeto já foi colocado em prática, com decisões construídas junto com controle social. Existem 30.824 ofertas de equipamentos sociais que visam potencializar a proteção social à população através dos serviços, programas, projetos e benefícios dessa política. As conquistas convivem com problemas e contradições, assim, identificar e construir alternativas para esses desafios também faz parte do planejamento contínuo desta política pública.

A Assistência Social teve sua estruturação iniciada com a Constituição Federal de 1988 (CRFB 88), quando passou a ser compreendida como direito do cidadão brasileiro e, portanto, como uma política pública de responsabilidade do Estado. Uma política de Seguridade Social não contributiva, que visa, em conjunto com outras políticas setoriais, a universalização dos direitos sociais.

O Sistema Único de Assistência Social (SUAS), tem suas ações fundadas na gestão descentralizada e participativa, com gestão compartilhada, cofinanciamento e cooperação técnica entre os três entes federados. Além da União, estados e municípios, o SUAS é integrado pelos Conselhos de Assistência Social e pelas entidades e organizações de Assistência Social. Sua organização está disposta na Lei Orgânica da Assistência Social (LOAS), de 7 de dezembro de 1993, em conformidade com a Política Nacional de Assistência Social (PNAS).

No SUAS estão previstos dois tipos de proteção social: a Básica e a Especial, respectivamente, para prevenção de situações de vulnerabilidade e enfrentamento de situações de violações de direitos, respectivamente. Nele também são ofertados os benefícios assistenciais. As ações são empreendidas tanto pelas unidades públicas e pela rede socioassistencial privada do SUAS.

Até atingir a forma atual de organização, a Assistência Social passou por mudanças significativas, consequência de inúmeros esforços que possibilitaram a ampliação de recursos, programas, benefícios e serviços voltados à população em situação de vulnerabilidade e risco social e/ou violação de direitos.

Ao longo do século XXI, ainda que tenham sido instituídos alguns programas e elaboradas leis voltadas à proteção social, o acesso aos direitos sociais era baseado na capacidade contributiva do trabalhador, excluindo uma grande parcela da população, inclusive a parcela que trabalhava no mercado informal.

A partir de 1988, a Constituição Brasileira trouxe uma nova perspectiva para a proteção social, apresentando, pela primeira vez no Brasil, um modelo amplo de Seguridade Social, composto por Saúde, Previdência e Assistência Social, prevendo atendimento e cobertura universais. O modelo requer que os benefícios e serviços devem ser uniformes e equivalentes para a população rural e urbana. Prevê a integração entre governos, com participação dos três entes, e a sociedade para a consecução dos objetivos estipulados.

A Assistência Social foi reconhecida, portanto, como um direito da pessoa que dela precisar, sem necessidade de contribuição prévia à Seguridade Social. Tem por objetivos, de acordo com a Constituição Federal, "a proteção à família, à maternidade, à infância, à adolescência e à velhice; o amparo às crianças e adolescentes carentes; a promoção da integração ao mercado de trabalho; a habilitação e reabilitação das pessoas portadoras de deficiência e a promoção de sua integração à vida comunitária; e a garantia de um salário mínimo de benefício mensal à pessoa portadora de deficiência e ao idoso que comprovem não possuir meios de prover à própria manutenção ou de tê-la provida por sua família".[^apresentacao-1]

[^apresentacao-1]: BRASIL. Constituição da República Federativa do Brasil de 1988. Disponível em: <http://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm>. Acesso em 09/08/2018.

Considerando a nova configuração da Assistência Social definida pela CRFB 88, foi sancionada, em 7 de dezembro de 1993, a Lei nº 8.742 - Lei Orgânica da Assistência Social (LOAS) que estabelece os princípios de universalização dos direitos sociais, com igualdade de direitos de acesso no atendimento e respeito à dignidade do cidadão. Dispondo sobre a nova organização da Assistência Social, a lei trouxe inovações importantes, como a participação social por meio de instâncias de controle social e a descentralização político-administrativa com primazia da responsabilidade do Estado, nas três esferas de governo, e na condução da política, bem como o cofinanciamento dos benefícios, serviços, programas e projetos da Assistência Social. Para tanto, faz-se fundamental a articulação e a coordenação entre os três entes da federação, que se dá por meio das Comissões Intergestores Tripartite (CIT) e Bipartite (CIB), instâncias de pactuação interfederativa para a operacionalização da gestão do SUAS.

A partir da LOAS, uma série de ferramentas de institucionalização foi organizada a fim de nortear a nova configuração da Assistência Social, como visto na @tbl-marcos.

| 1993 | 1998 | 2004 | 2005 | 2006 | 2009 | 2010 | 2011 | 2012 |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| LOAS     | PNAS     | PNAS     | NOB/ SUAS | NOB/ RH   | Tipificação dos Serviços | Decreto 7.334 Censo SUAS | Lei 12.435 SUAS | NOB/ SUAS |

: Marcos legais da Assistência Social no Brasil. {#tbl-marcos}

A primeira Política Nacional de Assistência Social (PNAS), prevista na LOAS, foi criada em 1998 e instituiu diretrizes para as ações da Assistência Social, representando uma base orientadora para os procedimentos a serem adotados pelos gestores da política de assistência social em todo o país[^apresentacao-2].

[^apresentacao-2]: BOSCHETTI, Ivanete (2001)

Em 2003[^apresentacao-3], a IV Conferência Nacional de Assistência Social deliberou sobre a construção e a implementação do Sistema Único de Assistência Social (SUAS).

[^apresentacao-3]: As Conferências de Assistência Social deliberam sobre as diretrizes para o aperfeiçoamento da Política de Assistência Social em cada uma das esferas governamentais (BRASIL, 2012).

Em 2004, a Resolução nº 145 do Conselho Nacional de Assistência Social (CNAS) aprova a PNAS e define elementos importantes para as políticas sociais, destacando-se o aperfeiçoamento da descentralização, a estruturação da participação da população, a fundamentação na centralidade na família para concepção e a implementação dos benefícios, programas e projetos

No ano seguinte, a Norma Operacional Básica do Sistema Único de Assistência Social (NOB SUAS), em conjunto com a PNAS 2004, representou importante avanço na consolidação e implementação das diretrizes previstas na LOAS e na CRFB 88. A NOB SUAS 2005 normatiza a operacionalização do Sistema Único de Assistência Social (SUAS), avançando na integração, pactuação e coordenação entre as esferas do governo, na organização das instâncias de gestão, na articulação e no controle da política, na proteção social, na instituição de arranjos para a prestação de serviços e no financiamento, definindo sobre os repasses regulares e mecanismos de transferências de recursos fundo a fundo baseada em pisos, critérios e indicadores de partilha[^apresentacao-4].

[^apresentacao-4]: Norma Operacional Básica NOB/SUAS. Construindo as bases para a implantação do Sistema Único de Assistência Social. Disponível em: <http://www.assistenciasocial.al.gov.br/sala-de-imprensa/arquivos/NOB-SUAS.pdf>. Acesso em 26/10/2017

A NOB/SUAS 2012 avançou na pactuação de metas e de resultados, e trouxe maior flexibilização para uso dos recursos, ampliando a autonomia dos municípios. Também trouxe avanços em relação à organização da Vigilância Socioassistencial e da gestão do trabalho, principalmente em relação à educação dos trabalhadores.

As diversas atualizações de normativos realizadas desde a promulgação da Constituição de 1988 definem aspectos de gestão, financiamento, organização da prestação dos serviços, oferta de benefícios, estrutura, recursos humanos e de participação social para a Assistência Social. Nesse sentido, destaca-se a importância do Censo SUAS como ferramenta de acompanhamento e monitoramento dos diversos elementos que compõem o SUAS.
